## logistic Regression for binary classification

In [21]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

In [22]:
df = pd.read_csv("C:/Users/Guru Kiran/All CSV files/Play Tennis.csv")
df.head(10)

   Day   Outlook Temprature Humidity    Wind Play_Tennis
0   D1     Sunny        Hot     High    Weak          No
1   D2     Sunny        Hot     High  Strong          No
2   D3  Overcast        Hot     High    Weak         Yes
3   D4      Rain       Mild     High    Weak         Yes
4   D5      Rain       Cool   Normal    Weak         Yes
5   D6      Rain       Cool   Normal  Strong          No
6   D7  Overcast       Cool   Normal  Strong         Yes
7   D8     Sunny       Mild     High    Weak          No
8   D9     Sunny       Cool   Normal    Weak         Yes
9  D10      Rain       Mild   Normal    Weak         Yes

In [23]:
# -----------------------------
# 2. Preprocessing
# -----------------------------
x = df.drop(columns=['Day','Play_Tennis'])   # features
y = df['Play_Tennis']                        # target

In [24]:
x= pd.get_dummies(X)

In [25]:
x.head()

   Outlook_Overcast  Outlook_Rain  Outlook_Sunny  ...  Humidity_Normal  Wind_Strong  Wind_Weak
0             False         False           True  ...            False        False       True
1             False         False           True  ...            False         True      False
2              True         False          False  ...            False        False       True
3             False          True          False  ...            False        False       True
4             False          True          False  ...             True        False       True

[5 rows x 10 columns]

In [26]:
# Split into Train/Test
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3,random_state=42,stratify=y)

In [27]:
# -----------------------------
# 3. Logistic Regression Model
# -----------------------------
log_reg = LogisticRegression()
model=log_reg.fit(x_train, y_train)

# Predictions
y_pred = model.predict(x_test)
y_prob = model.predict_proba(x_test)

In [28]:
# -----------------------------
# 4. Evaluation
# -----------------------------
print("Accuracy:", metrics.accuracy_score(y_test, y_pred))
print("\nConfusion Matrix:\n", metrics.confusion_matrix(y_test, y_pred))

Accuracy: 0.6

Confusion Matrix:
 [[0 2]
 [0 3]]

In [33]:
print("Classification Report",metrics.classification_report(y_test, y_pred))

Classification Report               precision    recall  f1-score   support

          No       0.00      0.00      0.00         2
         Yes       0.60      1.00      0.75         3

    accuracy                           0.60         5
   macro avg       0.30      0.50      0.38         5
weighted avg       0.36      0.60      0.45         5

C:\Users\Guru Kiran\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_classification.py:1706: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Users\Guru Kiran\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_classification.py:1706: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Users\Guru Kiran\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_classification.py:1706: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

## Logistic Regression for multi class classification

In [34]:
import pandas as pd
fish = pd.read_csv('C:/Users/Guru Kiran/All CSV files/dataset_Fish.csv')
fish.head()

  Species  Weight  Length1  Length2  Length3   Height   Width
0   Bream   242.0     23.2     25.4     30.0  11.5200  4.0200
1   Bream   290.0     24.0     26.3     31.2  12.4800  4.3056
2   Bream   340.0     23.9     26.5     31.1  12.3778  4.6961
3   Bream   363.0     26.3     29.0     33.5  12.7300  4.4555
4   Bream   430.0     26.5     29.0     34.0  12.4440  5.1340